services:
  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile.dev
    container_name: user-service-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL_POSTGRES}
    volumes:
      - ./apps/user-service/src:/usr/src/app/apps/user-service/src
      - ./apps/user-service/tsconfig.json:/usr/src/app/apps/user-service/tsconfig.json
      - ./apps/user-service/tsconfig.build.json:/usr/src/app/apps/user-service/tsconfig.build.json
      - ./packages:/usr/src/app/packages
      # Exclure le dossier node_modules des montages de volumes
      - /usr/src/app/apps/user-service/node_modules
    ports:
      - "3001:3001"
      - "4001:4001"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/docs"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  auth-service:
    volumes:
      - ./apps/auth-service/src:/usr/src/app/apps/auth-service/src
      - ./apps/auth-service/tsconfig.json:/usr/src/app/apps/auth-service/tsconfig.json
      - ./apps/auth-service/tsconfig.build.json:/usr/src/app/apps/auth-service/tsconfig.build.json
      - ./packages:/usr/src/app/packages
      # Exclure le dossier node_modules des montages de volumes
      - /usr/src/app/apps/auth-service/node_modules 