# La version est supprimée car obsolète dans les dernières versions de Docker Compose

version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: advanced-web-project-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network

  redis:
    image: redis:7
    container_name: advanced-web-project-redis
    ports:
      - "6379:6379"
    networks:
      - internal-network

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile.dev
    container_name: user-service-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/user_service?schema=public
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./apps/user-service:/app/apps/user-service
      - /app/apps/user-service/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - internal-network
    command: sh -c "cd apps/user-service && npm install && npx nest start --watch"

  product-service:
    build:
      context: .
      dockerfile: apps/product-service/Dockerfile.dev
    container_name: product-service-dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/user_service?schema=public
    volumes:
      - ./apps/product-service:/app/apps/product-service
      - /app/apps/product-service/node_modules
    depends_on:
      - postgres
    networks:
      - internal-network
    command: sh -c "cd apps/product-service && npm install && npx nest start --watch"

  delivery-service:
    build:
      context: .
      dockerfile: apps/delivery-service/Dockerfile.dev
    container_name: delivery-service-dev
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/user_service?schema=public
    volumes:
      - ./apps/delivery-service:/app/apps/delivery-service
      - /app/apps/delivery-service/node_modules
    depends_on:
      - postgres
    networks:
      - internal-network
    command: sh -c "cd apps/delivery-service && npm install && npx nest start --watch"

volumes:
  postgres_data:

networks:
  internal-network:
    driver: bridge 