services:
  postgres-db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${DATABASE_MDP_POSTGRES}
      POSTGRES_DB: ${DATABASE_NAME_POSTGRES}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      USER_SERVICE_URL: http://user-service:3001
    ports:
      - "3001:3001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - postgres-db
      - auth-service
      - product-service
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_POSTGRES}
      AUTH_SERVICE_URL: http://auth-service:3001
      PRODUCT_SERVICE_URL: http://product-service:3002
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - api_gateway_logs:/var/log/nginx

  product-service:
    build:
      context: .
      dockerfile: apps/product-service/Dockerfile
    container_name: product-service
    restart: unless-stopped
    depends_on:
      - postgres-db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_POSTGRES}
    ports:
      - "3002:3002"
    networks:
      - app-network
    volumes:
      - ./packages/prisma:/app/packages/prisma
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  redis_data:
  api_gateway_logs:

networks:
  app-network:
    driver: bridge
