services:
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${DATABASE_MDP_POSTGRES}
      POSTGRES_DB: ${DATABASE_NAME_POSTGRES}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      USER_SERVICE_URL: http://user-service:3001
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - postgres
      - user-service
      - auth-service
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_POSTGRES}
      AUTH_SERVICE_URL: http://auth-service:3001
      USER_SERVICE_URL: http://user-service:3001
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - api_gateway_logs:/var/log/nginx

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    container_name: user-service
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL_POSTGRES}
    networks:
      - app-network
    #  healthcheck:
    #    test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/health"]
    #    interval: 10s
    #    timeout: 5s
    #    retries: 3
    #    start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      - api-gateway
    ports:
      - "8080:80"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  api_gateway_logs:

networks:
  app-network:
    driver: bridge
