FROM node:18-slim

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Installer les dépendances de compilation
RUN apt-get update && \
    apt-get install -y build-essential python3 && \
    rm -rf /var/lib/apt/lists/*

# Copier les fichiers essentiels pour l'installation
# Copier package.json de la racine et du microservice
COPY package.json ./
COPY apps/order-service/package.json ./apps/order-service/
# Copier les packages locaux
COPY packages/ ./packages/

# Installer les dépendances en utilisant les packages locaux
# On se place d'abord dans le répertoire racine pour créer les liens symboliques
RUN npm install --legacy-peer-deps
# Puis on installe les dépendances du microservice
WORKDIR /usr/src/app/apps/order-service
RUN npm install --legacy-peer-deps

# Créer des liens symboliques pour le PrismaService si nécessaire
RUN mkdir -p /usr/src/app/apps/order-service/src/prisma
# Utiliser un lien symbolique pour que les modifications soient reflétées en temps réel
RUN ln -sf /usr/src/app/packages/prisma/src/prisma.service.ts /usr/src/app/apps/order-service/src/prisma/prisma.service.ts
RUN ln -sf /usr/src/app/packages/prisma/src/index.ts /usr/src/app/apps/order-service/src/prisma/index.ts

# Exposer le port du service
EXPOSE 3002

# Utiliser ts-node-dev directement au lieu de npm run pour éviter l'erreur de module non trouvé
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/main.ts"] 