# Utilisation de l'image officielle Node.js
FROM node:18-alpine

# Définir le répertoire de travail principal au niveau du monorepo
WORKDIR /app

# Copier uniquement les fichiers essentiels pour éviter un cache inutile
COPY package.json package-lock.json ./
COPY turbo.json ./
COPY apps/user-service ./apps/user-service
COPY packages ./packages

# Installer toutes les dépendances du monorepo
RUN npm install

# 📌 Se déplacer dans le dossier correct du microservice
WORKDIR /app/apps/user-service

# Construire l'application NestJS
RUN npm run build

# Exposer le bon port (3001 pour Swagger)
EXPOSE 3001

# Démarrer l'application en mode production
CMD ["npm", "run", "start:prod"]
