FROM node:20-slim

# Create app directory
WORKDIR /usr/src/app

# Installation des dépendances système nécessaires pour Prisma et le diagnostic
RUN apt-get update -y && apt-get install -y openssl netcat-openbsd iproute2 iputils-ping

# Installation globale des outils nécessaires
RUN npm install -g typescript ts-node @nestjs/cli rimraf

# Installation de tsconfig-paths globalement pour résoudre les problèmes de chemins
RUN npm install -g tsconfig-paths

# Les dépendances seront installées à partir des volumes montés
# et la commande d'exécution sera fournie par docker-compose

# Exposer les ports
EXPOSE 3001
EXPOSE 4001

# Pas de CMD ici, il sera fourni par docker-compose 