FROM node:20.11.0 as development

# Create app directory
WORKDIR /usr/src/app

# Installer NestJS CLI globalement
RUN npm install -g @nestjs/cli

# Copy root package files and install dependencies
COPY package*.json ./
COPY tsconfig*.json ./
COPY turbo.json ./

# Copier les packages locaux avant l'installation
COPY ./packages/ ./packages/

# Installer les dépendances à la racine
RUN npm install

# Copy user-service
COPY ./apps/user-service ./apps/user-service

# Installer les dépendances manquantes manuellement dans le service utilisateur
WORKDIR /usr/src/app/apps/user-service
RUN npm install @nestjs/swagger bcrypt @types/bcrypt class-validator swagger-ui-express

# Retourner à la racine pour générer Prisma
WORKDIR /usr/src/app

# Generate Prisma client
RUN npx prisma generate --schema=./packages/prisma/prisma/schema.prisma

# Modifications du fichier main.ts pour s'assurer que le service écoute sur toutes les interfaces
RUN sed -i 's/host: '"'"'127.0.0.1'"'"'/host: '"'"'0.0.0.0'"'"'/' ./apps/user-service/src/main.ts
RUN sed -i 's/await httpApp\.listen(3001)/await httpApp\.listen(3001, "0.0.0.0")/' ./apps/user-service/src/main.ts

# Create directory for PrismaService if not exists
RUN mkdir -p /usr/src/app/apps/user-service/src/prisma

# Create a modified version of the PrismaService if not exists
RUN if [ ! -f /usr/src/app/apps/user-service/src/prisma/prisma.service.ts ]; then \
    echo 'import { Injectable, OnModuleInit, OnModuleDestroy } from "@nestjs/common";\n\
import { PrismaClient } from "@prisma/client";\n\
\n\
@Injectable()\n\
export class PrismaService extends PrismaClient implements OnModuleInit, OnModuleDestroy {\n\
  async onModuleInit() {\n\
    await this.$connect();\n\
  }\n\
\n\
  async onModuleDestroy() {\n\
    await this.$disconnect();\n\
  }\n\
}' > /usr/src/app/apps/user-service/src/prisma/prisma.service.ts; \
fi

# Create an index file to export the service if not exists
RUN if [ ! -f /usr/src/app/apps/user-service/src/prisma/index.ts ]; then \
    echo 'export * from "./prisma.service";' > /usr/src/app/apps/user-service/src/prisma/index.ts; \
fi

# Change working directory to user-service
WORKDIR /usr/src/app/apps/user-service

# Exposer le port
EXPOSE 3001
EXPOSE 4001

# Run the service
CMD ["npm", "run", "start:dev"] 