FROM node:18-slim

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Installer les dépendances de compilation
RUN apt-get update && \
    apt-get install -y build-essential python3 && \
    rm -rf /var/lib/apt/lists/*

# Copier les fichiers package.json
COPY package*.json ./
COPY packages/prisma/package*.json ./packages/prisma/
COPY apps/user-service/package*.json ./

# Installer les dépendances
RUN npm install --legacy-peer-deps

# Copier le code source
COPY packages/prisma ./packages/prisma
COPY apps/user-service ./apps/user-service
COPY tsconfig.json ./
COPY turbo.json ./

# Générer le client Prisma
RUN npx prisma generate --schema=./packages/prisma/prisma/schema.prisma

# Build de l'application
RUN npm run build user-service

# Exposer les ports
EXPOSE 3001
EXPOSE 4001

# Démarrer l'application
CMD ["node", "dist/apps/user-service/src/main.js"]
