FROM node:20-slim

WORKDIR /usr/src/app

# Installation des dépendances système nécessaires
RUN apt-get update && \
    apt-get install -y build-essential python3 && \
    rm -rf /var/lib/apt/lists/*

# Copie des fichiers de configuration
COPY package*.json ./
COPY packages/prisma/package*.json ./packages/prisma/
COPY apps/product-service/package*.json ./apps/product-service/

# Installation des dépendances
RUN npm install --legacy-peer-deps

# Copie des fichiers source
COPY packages/prisma ./packages/prisma
COPY apps/product-service ./apps/product-service
COPY tsconfig.json ./
COPY turbo.json ./

# Génération du client Prisma
RUN npx prisma generate --schema=./packages/prisma/prisma/schema.prisma

EXPOSE 3002

CMD ["sh", "-c", "cd apps/product-service && npm install && npx nest start --watch"] 