FROM node:18-slim

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Installer les dépendances de compilation
RUN apt-get update && \
    apt-get install -y build-essential python3 && \
    rm -rf /var/lib/apt/lists/*

# Installer NestJS CLI globalement
RUN npm install -g @nestjs/cli

# Copier les fichiers essentiels pour l'installation
# Copier package.json de la racine et du microservice
COPY package.json ./
COPY apps/api-gateway/package.json ./apps/api-gateway/
# Copier les packages locaux
COPY packages/ ./packages/

# Installer les dépendances en utilisant les packages locaux
# On se place d'abord dans le répertoire racine pour créer les liens symboliques
RUN npm install --legacy-peer-deps
# Puis on installe les dépendances du microservice
WORKDIR /usr/src/app/apps/api-gateway
RUN npm install --legacy-peer-deps

# Exposer le port du service
EXPOSE 3000

# Utiliser ts-node-dev directement au lieu de npm run pour éviter l'erreur de module non trouvé
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/main.ts"] 