FROM node:18-slim

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Installer les dépendances de compilation et OpenSSL pour les certificats
RUN apt-get update && \
    apt-get install -y build-essential python3 openssl nginx && \
    rm -rf /var/lib/apt/lists/*

# Créer les répertoires nécessaires pour NGINX et les logs
RUN mkdir -p /var/log/nginx /run/nginx /etc/nginx/ssl

# Copier les fichiers essentiels pour l'installation
COPY package.json ./
COPY apps/api-gateway/package.json ./apps/api-gateway/
COPY packages/ ./packages/

# Installer les dépendances
RUN npm install --legacy-peer-deps
WORKDIR /usr/src/app/apps/api-gateway
RUN npm install --legacy-peer-deps

# Copier les fichiers de configuration NGINX
COPY apps/api-gateway/nginx.conf /etc/nginx/nginx.conf
COPY apps/api-gateway/ssl.conf /etc/nginx/conf.d/default.conf
COPY apps/api-gateway/nginx-main.conf /etc/nginx/conf.d/main.conf

# Copier le script de génération de certificats SSL et le rendre exécutable
COPY apps/api-gateway/generate-ssl-certs.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/generate-ssl-certs.sh

# Copier le script de démarrage et le rendre exécutable
COPY apps/api-gateway/start.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/start.sh

# Exposer les ports pour HTTP et HTTPS
EXPOSE 80 443 3000

# Définir le script de démarrage
ENTRYPOINT ["/usr/local/bin/start.sh"] 