FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de l'application
COPY package.json package-lock.json ./
COPY apps/api-gateway/package.json apps/api-gateway/
RUN npm install --legacy-peer-deps

COPY apps/api-gateway apps/api-gateway/
COPY packages packages/
COPY turbo.json ./

# Construire l'application
RUN npm run build --workspace=apps/api-gateway

WORKDIR /app/apps/api-gateway

# Exposer le port de l'application
EXPOSE 3000

# Démarrer l'application
CMD ["node", "dist/main.js"] 